Fix MSVC error
Compiling the current master with MSVC gives the following error:

```
search.cpp(956): error C2660: 'operator *': function does not take 1
arguments
types.h(303): note: see declaration of 'operator *'
```

This was introduced in commit:
88de112

We use a suggestion by @vondele to fix the error, thanks!

No functional change.
master
mstembera
@snicolet
mstembera authored